// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nfoiobjfyyeqmhqngprr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5mb2lvYmpmeXllcW1ocW5ncHJyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAzMzI4NzUsImV4cCI6MjA2NTkwODg3NX0.2DD8x860xhc7DJx-LFQQTm4WcXgdTWiaaHn4YkbklQc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);